---
image: nodered
version: v1.1.19
name: Node-red
description: "[Node-Red](https://nodered.org/)  is a programming tool for wiring together hardware devices, APIs and online services in new and interesting ways."
ext_release: 3.1.9
arch:
  - aarch64
  - x86_64
