#!/usr/bin/with-contenv bash
# shellcheck shell=bash

export NODE_PATH=/opt/node_modules:/data/node_modules
declare -a options
declare max_old_space_size

options+=(--settings "/etc/node-red/config.js")

exec \
    s6-notifyoncheck -d -n 300 -w 1000 \
        cd /opt/ s6-setuidgid root npm start -- "${options[@]}"
